### ISSUE TITLE
Ionic serve failing in mac

### ISSUE THREAD

**Issue by sankaran85** [ionic-team/ionic-conference-app#454]
Short description of the problem:

App not working in mac pro when i run ionic serve.

What behavior are you expecting?

It to work.

Steps to reproduce:

1. git clone
2. npm install
3. ionic serve 
Gets the following console errors and the app is just white:

Cant resolve all parameters for ActionSheetController: (?,?)

$ ionic info

Your system information:
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.1

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.1-201710301651
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.8.0-201710302049

System:
    Node  : v6.11.4
    npm   : 3.10.10 
    OS    : macOS High Sierra
    Xcode : Xcode 9.0.1 Build version 9A1004 
Misc:
    backend : pro

**Comment by drogers98** [comment]
I am also experiencing this exact issue.

**Comment by yaotzin68** [comment]
me too

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The app was using the `@nightly` versions of `ionic-angular` and `@ioninc/app-scripts` instead of the latest released versions. That is kinda dangerous since `@nightly` can contain any sort of experimental stuff, including stuff that doesn't actually work... :)

Please:
1. `git pull` on `master` for your clone
2. `rm -rf node_modules`
3. `npm i`

Let me know if that clears things up for you.

Thank you for using Ionic

**Comment by sankaran85** [comment]
Thanks works fine in master ... but the lazy-load branch still points to @nightly ?
