### ISSUE TITLE
Dead links on readme

### ISSUE THREAD

**Issue by Blunderchips** [ionic-team/ionic-conference-app#666]
Overly threating issue template aside, the readme is full of dead links.

**Comment by DevelopByM** [comment]
I will do this!

**Comment by brandyscarney** [comment]
The reason we have such detailed issue templates is to gather as much information as possible from you so that we can find and fix the reported issue faster. Otherwise we end up spending time going back and forth on an issue asking questions or attempting to find the problem ourselves. For example, in this issue it would have been helpful to include _which_ links are dead, so that we don't have to go through all of them to find which ones need to be fixed. 🙂

Thank you for wanting to take this on @DevelopByM!
